### ISSUE TITLE
Adam Week 2:

### ISSUE THREAD

**Issue by AdamHolbel** [error404csp/weather#5]
- Start login system for the user 
- Style Login page better
- [x] Complete Digital Portfolio
- [x] Study for next weeks AP Exam

Links To Help:
[Kailas Document](https://docs.google.com/document/d/1JO4-AmY5pNLwSPj45ztj9Q0lW-4nGi17Hg8hTVDGRc8/edit)

**Comment by maggie3000** [comment]
Nice frontend for the sign in page.
